spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blog
    username: root
    password: Tmdcjdahzk12#
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # JPA가 애플리케이션 시작 시 데이터베이스 스키마를 자동으로 업데이트합니다.
    show-sql: true  # SQL 쿼리를 로그에 출력하여 확인할 수 있게 합니다.

  thymeleaf:
    cache: false  # 개발 중에 템플릿 캐시 비활성화
    prefix: classpath:/templates/  # 템플릿 파일 경로 설정
    suffix: .html  # 템플릿 파일 확장자 설정
